name: WbsEnchants
version: '1.1'
main: wbs.enchants.WbsEnchants
description: WbsEnchants
api-version: '1.21.1'
bootstrapper: wbs.enchants.WbsEnchantsBootstrap
dependencies:
  bootstrap:
    WbsUtils:
      load: BEFORE
      required: true
  server:
    WbsUtils:
      load: BEFORE
      required: true
