name: WbsEnchants
version: 1.0
api-version: 1.21
main: wbs.enchants.WbsEnchants
description: Yet another custom enchants plugin
depend:
  - WbsUtils
commands:
  customenchants:
    aliases:
      - cench
      - cenchant
      - cenchants
      - cenchantment
      - customenchant
    description: Interact with and get information about custom enchantments